codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
  hide_project_coverage: false
